AWSTemplateFormatVersion: "2010-09-09"

Resources:

  CollectorSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Collector server
      GroupName: CollectorSecurityGroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000 # Grafana
          ToPort: 3000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8086 # InfluxDB
          ToPort: 8086
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22 # SSH
          ToPort: 22
          CidrIp: 0.0.0.0/0

  CollectorServer:
    Type: AWS::EC2::Instance
    DependsOn:
      - DeploymentProfile
      - DeploymentRole
      - DeploymentPolicy
    Properties:
      InstanceType: t3.small
      ImageId: ami-06fd8a495a537da8b # Ubuntu Server 20.04 LTS (HVM), SSD Volume Type
      KeyName: collector-server
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeType: gp2
            VolumeSize: '20'
            Encrypted: 'true'
      SecurityGroupIds:
        - !Ref CollectorSecurityGroup
      IamInstanceProfile: !Ref DeploymentProfile
      UserData:
        !Base64 |
        #!/bin/bash
        # log UserData script output, source: https://alestic.com/2010/12/ec2-user-data-output/
        exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
        echo ----- start UserData script -----
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get install awscli -y
        echo ----- call install.sh script -----
        aws s3 cp s3://collector-deployment-bucket-m1mgfnap/deployment/install.sh - | bash
        echo ----- end UserData script -----

  DeploymentProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles: [!Ref DeploymentRole]

  DeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com]
            Action: ['sts:AssumeRole']
      Path: /

  DeploymentPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: DeploymentPolicy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: [
                's3:List*',
                's3:GetObject',
                'ssm:GetParameters'
            ]
            Resource: [
                'arn:aws:s3:::collector-deployment-bucket-m1mgfnap',
                'arn:aws:s3:::*/*',
                'arn:aws:ssm:eu-west-1:060337561279:parameter/Collector/InfluxDB_Users',
            ]
      Roles:
        - !Ref DeploymentRole

Outputs:
  CollectorServerIP4DNS:
    Value: !GetAtt CollectorServer.PublicDnsName
