AWSTemplateFormatVersion: "2010-09-09"
Resources:

  CollectorSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Collector server
      GroupName: CollectorSecurityGroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  CollectorServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t4g.small
      ImageId: ami-036559f6f83de21be
      KeyName: collector-server
      SecurityGroupIds:
        - !Ref CollectorSecurityGroup
